# build stage
FROM harbor.onwalk.net/knative/alpine:3.14

WORKDIR /app
ADD repositories /etc/apk/repositories
RUN apk --update add nodejs npm
RUN npm config set registry https://registry.npm.taobao.org 

COPY package*.json ./
RUN npm install
COPY . .
#RUN npm run build
